language: julia

sudo: false

os:
  - linux
  - osx

julia:
  - 0.5
  - 0.6
  # - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - julia: 0.6

script:
  - julia -e 'Pkg.clone(pwd());' 
  - julia -e 'Pkg.test("KernelRidgeRegression", coverage = true)'

after_success:
  - julia -e 'if is_linux() cd(Pkg.dir("KernelRidgeRegression")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()) end'
  - julia -e 'Pkg.status("KernelRidgeRegression")'

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
