language: julia

sudo: required

os:
  - linux
  - osx

julia:
  - 0.5
  # - 0.6
  # - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - julia: 0.6

install:
  - sudo apt-get install liblapack-dev
  - sudo pip install --upgrade --user pip
  - pip install --user scipy
  - pip install --user numpy
  - pip install --user climin
  - pip install --user cython
  - pip install --user gpy 

script:
  - export PYTHON=""
  - julia -e 'Pkg.clone(pwd());' 
  - julia -e 'Pkg.test("KernelRidgeRegression", coverage = true)'

after_success:
  - julia -e 'if is_linux() cd(Pkg.dir("KernelRidgeRegression")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()) end'
  - julia -e 'Pkg.status("KernelRidgeRegression")'

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
